import fs from "node:fs/promises";
import path from "node:path";
import type { ResolvedOptions } from "./types.js";

interface RuntimeExport {
    readonly exportName: string;
    readonly signature: string;
    readonly parameterTypes: readonly string[];
    readonly returnType: string;
    readonly exposedName?: string;
}

export async function generateRuntime(functions: readonly RuntimeExport[], options: ResolvedOptions): Promise<string> {
    const runtimePath = path.join(options.generatedDirectory, `${options.moduleName}.ts`);
    const fields = functions.map(({ exportName, signature }) => `  readonly ${exportName}: ${signature};`).join("\n");
    const rawFields = functions
        .map(({ exportName, parameterTypes, returnType }) => {
            const parameters = parameterTypes.map((type, index) => `value${index}: ${rawType(type)}`).join(", ");
            return `  readonly ${exportName}: (${parameters}) => ${rawType(returnType)};`;
        })
        .join("\n");
    const wrappers = functions
        .map(({ exportName, parameterTypes, returnType }) => {
            const parameters = parameterTypes.map((type, index) => `value${index}: ${javascriptType(type)}`).join(", ");
            const argumentsList = parameterTypes.map((type, index) => convertArgument(type, index)).join(", ");
            const call = `rawWasm.${exportName}(${argumentsList})`;
            return `  ${exportName}(${parameters}): ${javascriptType(returnType)} {\n    return ${convertResult(returnType, call)};\n  },`;
        })
        .join("\n");
    const exposedNameCounts = new Map<string, number>();
    for (const { exposedName } of functions) {
        if (exposedName) exposedNameCounts.set(exposedName, (exposedNameCounts.get(exposedName) ?? 0) + 1);
    }
    const namedFields = functions
        .filter(({ exposedName }) => exposedName && exposedNameCounts.get(exposedName) === 1)
        .map(({ exposedName, exportName }) => `  ${exposedName}: wasm.${exportName},`)
        .join("\n");
    const source = `// Generated by WasmScript. Do not edit.\n\nexport interface WasmExports {\n  readonly memory: WebAssembly.Memory;\n${fields}\n}\n\ninterface RawWasmExports {\n  readonly memory: WebAssembly.Memory;\n${rawFields}\n}\n\nconst response = await fetch(new URL("./${options.wasmFileName}", import.meta.url));\nconst bytes = await response.arrayBuffer();\nconst imports = {\n  env: {\n    abort(_message: number, _file: number, line: number, column: number): never {\n      throw new Error(\`AssemblyScript aborted at \${line}:\${column}\`);\n    },\n  },\n};\nconst result = await WebAssembly.instantiate(bytes, imports);\nconst rawWasm = result.instance.exports as unknown as RawWasmExports;\n\nexport const wasm: WasmExports = {\n  memory: rawWasm.memory,\n${wrappers}\n};\nexport const memory = wasm.memory;\n\nexport function createF64View(byteOffset: number, length: number): Float64Array {\n  return new Float64Array(memory.buffer, byteOffset, length);\n}\n\nexport function createI32View(byteOffset: number, length: number): Int32Array {\n  return new Int32Array(memory.buffer, byteOffset, length);\n}\n\nexport const namedWasm = {\n${namedFields}\n} as const;\n`;

    const runtimeSource = source.replace(
        "export function createF64View",
        `function liftString(pointer: number): string {
  if (pointer === 0) return "";
  const byteLength = new Uint32Array(memory.buffer, pointer - 4, 1)[0]!;
  const characters = new Uint16Array(memory.buffer, pointer, byteLength / 2);
  let value = "";
  const chunkSize = 4096;
  for (let offset = 0; offset < characters.length; offset += chunkSize) {
    value += String.fromCharCode(...characters.subarray(offset, offset + chunkSize));
  }
  return value;
}

export function createF64View`,
    );
    await fs.mkdir(options.generatedDirectory, { recursive: true });
    await fs.writeFile(runtimePath, runtimeSource, "utf8");
    return runtimePath;
}

export async function generateScalarTypes(options: ResolvedOptions): Promise<string> {
    const typesPath = path.join(options.generatedDirectory, "_wasm$types.d.ts");
    const source = `// Generated by WasmScript. Do not edit.\ntype bool = boolean;\ntype f32 = number;\ntype f64 = number;\ntype i8 = number;\ntype i16 = number;\ntype i32 = number;\ntype i64 = number;\ntype isize = number;\ntype u8 = number;\ntype u16 = number;\ntype u32 = number;\ntype u64 = number;\ntype usize = number;\ndeclare class StaticArray<T> {\n  constructor(length: number);\n  [index: number]: T;\n}\ndeclare function changetype<T>(value: unknown): T;\n`;
    await fs.mkdir(options.generatedDirectory, { recursive: true });
    await fs.writeFile(typesPath, source, "utf8");
    return typesPath;
}

function rawType(type: string): string {
    return type === "i64" || type === "u64" ? "bigint" : type === "void" ? "void" : "number";
}

function javascriptType(type: string): string {
    if (type === "bool") return "boolean";
    if (type === "string") return "string";
    return type === "void" ? "void" : "number";
}

function convertArgument(type: string, index: number): string {
    if (type === "bool") return `value${index} ? 1 : 0`;
    if (type === "i64" || type === "u64") return `BigInt(value${index})`;
    return `value${index}`;
}

function convertResult(type: string, call: string): string {
    if (type === "bool") return `${call} !== 0`;
    if (type === "string") return `liftString(${call})`;
    if (type === "i64" || type === "u64") return `Number(${call})`;
    return call;
}
